
CREATE TABLE CAD_SOLICITACOES
(
  CODIGO          NUMBER NOT NULL,
  STATUS          NUMBER DEFAULT 0,
  PRIORIDADE      NUMBER,
  DT_VIGENCIA     DATE NOT NULL,
  SOLICITANTE     VARCHAR(60),
  DT_SOLICITACAO  DATE DEFAULT SYSDATE,
  DESCRICAO_MAT   VARCHAR(200),
  TIPO_MAT        NUMBER,
  FLG_MANIPULADO  CHAR(1),/*S - SIM / N - NÃO*/
  FORMA_AP_CODIGO VARCHAR(10),
  COD_ANVISA      NUMBER,
  REF_FABRICANTE  NUMBER,
  TIPO_DEMANDA    NUMBER,
  FLG_FRACIONA    CHAR(1),
  FLG_MOV_ESTOQUE CHAR(1),
  FLG_MOV_SUB_EST CHAR(1),
  CENTRO_DE_CUSTO NUMBER,
  COD_AGENDA_CCIR NUMBER,
  NOME_MEDICO     VARCHAR(100),
  FLG_ORCAMENTO   CHAR(1),
  FLG_AGENDAMENTO CHAR(1),
  CLASSIF_CONTAB  NUMBER,
  COD_GRUPO       NUMBER,
  COD_SUB_GRUPO   NUMBER
);
COMMENT ON COLUMN CAD_SOLICITACOES.TIPO_DEMANDA IS '1-CONSUMO/2-COMPRA/3-CONSIGNACAO/4-CONSIGNACAO-ESTOQUE';


CREATE TABLE cad_anexos
(
       cod_solicitacao NUMBER NOT NULL,
       seq_anexo       NUMBER NOT NULL,
       nome_arquivo    VARCHAR(150) NOT NULL,
       path_anexo      VARCHAR(300) NOT NULL
);


CREATE TABLE CAD_SOLICITACOES_CONTROLE
(
    COD_SOLICITACAO NUMBER NOT NULL,   
    SEQ_controle    NUMBER NOT NULL,       
    STATUS_solicit  NUMBER,
    USUARIO         VARCHAR(30) NOT NULL,
    DT_CONTROLE     DATE DEFAULT SYSDATE,
    OBSERVACAO      VARCHAR(400)
);

       
